// Mocks generated by Mockito 5.4.4 from annotations
// in pragma_cats/test/feed_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pragma_cats/data/services/breeds_service.dart' as _i2;
import 'package:pragma_cats/models/cat_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BreedsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBreedsService extends _i1.Mock implements _i2.BreedsService {
  MockBreedsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CatModel>?> listCatBreeds(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #listCatBreeds,
          [page],
        ),
        returnValue: _i3.Future<List<_i4.CatModel>?>.value(),
      ) as _i3.Future<List<_i4.CatModel>?>);

  @override
  _i3.Future<List<_i4.CatModel>?> search(String? search) => (super.noSuchMethod(
        Invocation.method(
          #search,
          [search],
        ),
        returnValue: _i3.Future<List<_i4.CatModel>?>.value(),
      ) as _i3.Future<List<_i4.CatModel>?>);
}
